### ISSUE TITLE
BGM on/off 기능 추가 요청

### ISSUE THREAD

**Issue by arabove** [bandochecard/bandochecard.github.io#21]
https://github.com/bandochecard/bandochecard.github.io/commit/3e7b766434e146099edde741ac90acd4582c8cfd

들어가자마자 BGM 재생이라니 이어폰이 없었으면 큰일날뻔 했잖아욧! (빼애액.....)

기본 설정 off로 해두시는 것도 잊지 말아주세요...?

**Comment by e2goon** [comment]
@arabove 했다능! 언능 close issue 처리 해달라능!

**Comment by arabove** [comment]
모바일에서 확인 완료했슴다 😋
